#########################################################
## 'Validate module with Pester' Composite Action      ##
#########################################################
##
## This composite action contains the logic to validate a module using a set of Pester tests
##
#########################################################
##
##-------------------------------------------##
## ACTION PARAMETERS                         ##
##-------------------------------------------##
##
##   |==================================================================================================================================================|
##   | Parameter                | Required | Default | Description                          | Example                                                   |
##   |--------------------------|----------|---------|--------------------------------------|-----------------------------------------------------------|
##   | modulePath               | true     | ''      | The path to the module's folder      | 'modules/api-management/service'                          |
##   | moduleTestFilePath       | true     | ''      | The path to the module Pester tests. | 'utilities/pipelines/staticValidation/module.tests.ps1'   |
##   |==================================================================================================================================================|
##
##---------------------------------------------##

name: 'Execute Pester module tests'
description: 'Execute Pester module tests (if any)'

inputs:
  modulePath:
    description: "The path to the module's folder"
    required: true
    default: ''
  moduleTestFilePath:
    description: 'The path to the test file'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    # [Module Pester Test] task(s)
    #-----------------------------
    - name: 'Run Pester tests'
      id: pester_run_step
      shell: pwsh
      run: |
        # Grouping task logs
        Write-Output '::group::Run Pester tests'

        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'staticValidation' 'Set-PesterGitHubOutput.ps1')

        # Set repo root path
        $repoRootPath = $env:GITHUB_WORKSPACE

        # Set test input module path
        $moduleFolderPaths = @(Join-Path $repoRootPath "${{ inputs.modulePath }}")
        $moduleFolderPaths += (Get-ChildItem $moduleFolderPaths -Recurse -Directory -Force).FullName | Where-Object {
          (Get-ChildItem $_ -File -Depth 0 -Include @('main.json', 'main.bicep') -Force).Count -gt 0
        }
        Write-Verbose 'Execute tests in path(s):' -Verbose
        foreach ($moduleFolderPath in $moduleFolderPaths) {
          Write-Verbose "- [($moduleFolderPath]" -Verbose
        }

        # Construct Token Configuration Input and enforced tokens list
        $GlobalVariablesObject = Get-Content -Path 'settings.yml' | ConvertFrom-Yaml | Select-Object -ExpandProperty variables
        $tokenConfiguration = @{
          Tokens      = @{}
          TokenPrefix = $GlobalVariablesObject | Select-Object -ExpandProperty tokenPrefix
          TokenSuffix = $GlobalVariablesObject | Select-Object -ExpandProperty tokenSuffix
        }

        if (-not [String]::IsNullOrEmpty('${{ env.ARM_SUBSCRIPTION_ID }}')) {
          $tokenConfiguration.Tokens['subscriptionId'] = '${{ env.ARM_SUBSCRIPTION_ID }}'
        }
        if (-not [String]::IsNullOrEmpty('${{ env.ARM_MGMTGROUP_ID }}')) {
          $tokenConfiguration.Tokens['managementGroupId'] = '${{ env.ARM_MGMTGROUP_ID }}'
        }
        if (-not [String]::IsNullOrEmpty('${{ env.ARM_TENANT_ID }}')) {
          $tokenConfiguration.Tokens['tenantId'] = '${{ env.ARM_TENANT_ID }}'
        }

        $moduleTestFilePath = '${{ inputs.moduleTestFilePath }}'

        # --------------------- #
        # Invoke Pester test(s) #
        # --------------------- #
        $pesterConfiguration = @{
          Run    = @{
            Container = New-PesterContainer -Path (Join-Path $repoRootPath $moduleTestFilePath) -Data @{
              moduleFolderPaths              = $moduleFolderPaths
              tokenConfiguration             = $tokenConfiguration
              allowPreviewVersionsInAPITests = [System.Convert]::ToBoolean('${{ env.allowPreviewVersionsInAPITests }}')
            }
            PassThru  = $true
          }
          Output = @{
            Verbosity = 'Detailed'
          }
        }

        Write-Verbose 'Invoke test with' -Verbose
        Write-Verbose ($pesterConfiguration | ConvertTo-Json -Depth 5 | Out-String) -Verbose

        $testResults = Invoke-Pester -Configuration $pesterConfiguration

        # ----------------------------------------- #
        # Create formatted Pester Test Results File #
        # ----------------------------------------- #

        $functionInput = @{
          PesterTestResults = $testResults
          OutputFilePath    = Join-Path $env:GITHUB_WORKSPACE 'Pester-output.md'
          GitHubRepository  = $env:GITHUB_REPOSITORY
          BranchName        = $env:GITHUB_REF
        }

        Write-Verbose 'Invoke Pester formatting function with' -Verbose
        Write-Verbose ($functionInput | ConvertTo-Json -Depth 0 | Out-String) -Verbose

        Set-PesterGitHubOutput @functionInput -Verbose

        Write-Output ('{0}={1}' -f 'formattedPesterResultsPath', $functionInput.outputFilePath) >> $env:GITHUB_OUTPUT

    - name: 'Output to GitHub job summaries'
      if: always()
      shell: pwsh
      run: |
        # Grouping task logs
        Write-Output '::group::Output to GitHub job summaries'

        $mdPesterOutputFilePath = '${{ steps.pester_run_step.outputs.formattedPesterResultsPath }}'

        if (-not (Test-Path $mdPesterOutputFilePath)) {
          Write-Warning ('Input file [{0}] not found. Please check if the previous task threw an error and try again.' -f $mdPesterOutputFilePath)
        } else {
          Get-Content $mdPesterOutputFilePath >> $env:GITHUB_STEP_SUMMARY
          Write-Verbose ('Successfully printed out file [{0}] to Job Summaries' -f $mdPesterOutputFilePath) -Verbose
        }

        Write-Output '::endgroup::'
