#########################################################
## 'Validate module with Pester' Composite Action      ##
#########################################################
##
## This composite action contains the logic to validate a module using a set of Pester tests
## The tests are implemented in file 'arm/.global/global.module.tests.ps1'
##
#########################################################
##
##-------------------------------------------##
## ACTION PARAMETERS                         ##
##-------------------------------------------##
##
##   |===========================================================================================================|
##   | Parameter  | Required | Default | Description                     | Example                               |
##   |------------|----------|---------|---------------------------------|---------------------------------------|
##   | modulePath | true     | ''      | The path to the module's folder | 'arm/Microsoft.ApiManagement/service' |
##   |===========================================================================================================|
##
##---------------------------------------------##

name: 'Execute Pester module tests'
description: 'Execute Pester module tests (if any)'

inputs:
  modulePath:
    description: "The path to the module's folder"
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: 'Setup agent'
      shell: pwsh
      run: |
        # Grouping task logs
        Write-Output "::group::Setup agent"

        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'sharedScripts' 'Set-EnvironmentOnAgent.ps1')

        # Define PS modules to install on the runner
        $Modules = @(
            # This is the latest tested Pester version. Uncomment the next line in case of a future breaking change in the default version installed on the runner.
            # @{ Name = 'Pester'; Version = '5.3.1' }
            @{ Name = 'Az.Resources' }
            @{ Name = 'powershell-yaml'; Version = '0.4.2'}
        )

        # Set agent up
        Set-EnvironmentOnAgent -PSModules $Modules

        Write-Output "::endgroup::"

    - name: 'Azure Login'
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    # [Module Pester Test] task(s)
    #-----------------------------
    - name: 'Run global tests via Pester'
      id: pester_run_step
      shell: pwsh
      run: |
        # Grouping task logs
        Write-Output "::group::Run global tests via Pester"

        $moduleFolderPaths = @(Join-Path $env:GITHUB_WORKSPACE "${{ inputs.modulePath }}")
        $moduleFolderPaths += (Get-ChildItem $moduleFolderPaths -Recurse -Directory -Force).FullName | Where-Object {
          (Get-ChildItem $_ -File -Depth 0 -Include @('deploy.json', 'deploy.bicep') -Force).Count -gt 0
        }
        Write-Verbose "Execute tests in path(s):" -Verbose
        foreach($moduleFolderPath in $moduleFolderPaths) {
          Write-Verbose "- [($moduleFolderPath]" -Verbose
        }

        $GlobalVariablesObject = Get-Content -Path 'global.variables.yml' | ConvertFrom-Yaml | Select-Object -ExpandProperty variables

        # Construct Token Configuration Input
        $tokenConfiguration = @{
            Tokens      = @{}
            TokenPrefix = $GlobalVariablesObject | Select-Object -ExpandProperty tokenPrefix
            TokenSuffix = $GlobalVariablesObject | Select-Object -ExpandProperty tokenSuffix
        }

        ## Enforced Tokens
        if (-not [String]::IsNullOrEmpty('${{ env.ARM_SUBSCRIPTION_ID }}')) {
            $tokenConfiguration.Tokens['subscriptionId'] = '${{ env.ARM_SUBSCRIPTION_ID }}'
        }
        if (-not [String]::IsNullOrEmpty('${{ env.ARM_MGMTGROUP_ID }}')) {
            $tokenConfiguration.Tokens['managementGroupId'] = '${{ env.ARM_MGMTGROUP_ID }}'
        }
        if (-not [String]::IsNullOrEmpty('${{ env.DEPLOYMENT_SP_ID }}')) {
            $tokenConfiguration.Tokens['deploymentSpId'] = '${{ env.DEPLOYMENT_SP_ID }}'
        }
        if (-not [String]::IsNullOrEmpty('${{ env.ARM_TENANT_ID }}')) {
            $tokenConfiguration.Tokens['tenantId'] = '${{ env.ARM_TENANT_ID }}'
        }

        ## Local Tokens from global.variables.yml
        foreach ($localToken in $GlobalVariablesObject.Keys | ForEach-Object { if ($PSItem.contains('localToken_')) { $PSItem } }) {
            $tokenConfiguration.Tokens[$localToken.Replace('localToken_', '')] = $GlobalVariablesObject.$localToken
        }

        # --------------------- #
        # Invoke Pester test(s) #
        # --------------------- #
        Invoke-Pester -Configuration @{
          Run        = @{
            Container = New-PesterContainer -Path 'arm/.global/global.module.tests.ps1' -Data @{
              moduleFolderPaths  = $moduleFolderPaths
              tokenConfiguration = $tokenConfiguration
            }
          }
          TestResult = @{
            TestSuiteName = 'Global Module Tests'
            OutputPath    = 'arm/.global/global-testResults.xml'
            OutputFormat  = 'JUnitXml'
            Enabled       = $true
          }
          Output     = @{
            Verbosity = 'Detailed'
          }
        }

    - name: 'Publish Test Results'
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: 'arm/.global/*-testResults.xml'
