name: 'Publish module'
description: 'Publish module'

inputs:
  templateFilePath:
    description: 'The path to the template file to publish'
    required: true
  templateSpecsRgName:
    description: 'Required to publish to template spec. ResourceGroup of the template spec to publish to'
    required: false
  templateSpecsRgLocation:
    description: 'Required to publish to template spec. Location of the template spec resource group'
    required: false
  templateSpecsDescription:
    description: 'Required to publish to template spec. Description of the template spec to publish to'
    required: false
  templateSpecsDoPublish:
    description: 'Flag to indicate whether or not to publish to template specs'
    default: 'false'
    required: false
  bicepRegistryName:
    description: 'Required to publish to private bicep registry. ResourceGroup of the container registry to publish to'
    required: false
  bicepRegistryRgName:
    description: 'Required to publish to private bicep registry. Name of the container registry resource group'
    required: false
  bicepRegistryRgLocation:
    description: 'Required to publish to private bicep registry. Location of the container registry resource group'
    required: false
  bicepRegistryDoPublish:
    description: 'Flag to indicate whether or not to publish to the private bicep registry'
    default: 'false'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Setup agent'
      shell: pwsh
      run: |
        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'sharedScripts' 'Set-EnvironmentOnAgent.ps1')

        # Define PS modules to install on the runner
        $Modules = @(
            @{ Name = 'Az.Accounts' },
            @{ Name = 'Az.ContainerRegistry' },
            @{ Name = 'Az.Resources' }
        )

        # Set agent up
        Set-EnvironmentOnAgent -PSModules $Modules

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: 'Publish module to template specs'
      shell: pwsh
      if: ${{ inputs.templateSpecsDoPublish == 'true' }}
      run: |
        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'resourcePublish' 'Get-ModulesToUpdate.ps1')
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'resourcePublish' 'Publish-ModuleToTemplateSpec.ps1')

        $functionInput = @{
          TemplateFilePath = Join-Path $env:GITHUB_WORKSPACE "${{ inputs.templateFilePath }}"
        }

        Write-Verbose "Invoke task with" -Verbose
        Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

        # Get the modified child resources
        $ModulesToUpdate = Get-ModulesToUpdate @functionInput -Verbose

        # Publish the modified child resources
        foreach ($ModuleToUpdate in $ModulesToUpdate) {
          $functionInput = @{
            TemplateFilePath         = $ModuleToUpdate.TemplateFilePath
            TemplateSpecsRgName      = '${{ inputs.templateSpecsRgName }}'
            TemplateSpecsRgLocation  = '${{ inputs.templateSpecsRgLocation }}'
            TemplateSpecsDescription = '${{ inputs.templateSpecsDescription }}'
            ModuleVersion            = $ModuleToUpdate.Version
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Publish-ModuleToTemplateSpec @functionInput -Verbose
        }

    - name: 'Publish module to private bicep registry'
      shell: pwsh
      if: ${{ inputs.bicepRegistryDoPublish == 'true' }}
      run: |
        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'resourcePublish' 'Get-ModulesToUpdate.ps1')
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'resourcePublish' 'Publish-ModuleToPrivateBicepRegistry.ps1')

        $functionInput = @{
          TemplateFilePath = Join-Path $env:GITHUB_WORKSPACE "${{ inputs.templateFilePath }}"
        }

        Write-Verbose "Invoke task with" -Verbose
        Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

        # Get the modified child resources
        $ModulesToUpdate = Get-ModulesToUpdate @functionInput -Verbose

        # Publish the modified child resources
        foreach ($ModuleToUpdate in $ModulesToUpdate) {
          $functionInput = @{
            TemplateFilePath        = $ModuleToUpdate.TemplateFilePath
            BicepRegistryName       = '${{ inputs.bicepRegistryName }}'
            BicepRegistryRgName     = '${{ inputs.bicepRegistryRgName }}'
            BicepRegistryRgLocation = '${{ inputs.bicepRegistryRgLocation }}'
            ModuleVersion           = $ModuleToUpdate.Version
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Publish-ModuleToPrivateBicepRegistry @functionInput -Verbose
        }
