name: 'Execute general module tests'
description: 'Execute general module tests (if any)'

inputs:
  modulePath:
    description: 'The path to the module folder'
    required: true
  moduleName:
    description: 'The name of the module to process'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Setup agent & login'
      shell: pwsh
      run: |
        # Load used functions
        . ".github/actions/sharedScripts/Set-EnvironmentOnAgent.ps1"
        # Set agent up
        Set-EnvironmentOnAgent

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    # [Module Pester Test] task(s)
    #-----------------------------
    - name: 'Run [${{ inputs.moduleName }}] tests via (Pester)'
      shell: pwsh
      run: |
        # --------------------- #
        # INVOKE PESTER TEST(S) #
        # --------------------- #
        Install-Module Pester -Force -ErrorAction Stop -RequiredVersion 5.3.0

        Invoke-Pester -Configuration @{
          Run        = @{
            Container = New-PesterContainer -Path 'arm/.global/global.module.tests.ps1' -Data @{
              moduleFolderPaths = Join-Path "$env:GITHUB_WORKSPACE" "${{ inputs.modulePath }}"
            }
          }
          Filter     = @{
            ExcludeTag = 'ApiCheck'
          }
          TestResult = @{
            TestSuiteName = 'Global Module Tests'
            OutputPath    = 'arm/.global/global-testResults.xml'
            OutputFormat  = 'JUnitXml'
            Enabled       = $true
          }
          Output     = @{
            Verbosity = 'Detailed'
          }
        }

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      # if: always()
      with:
        files: arm/.global/global-testResults.xml
