name: 'Authorization - PolicyExemptions'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.authorization.policyexemptions.yml'
      - '/.azuredevops/pipelineTemplates/module.*.yml'
      - '/arm/Microsoft.Authorization/policyExemptions/*'
    exclude:
      - '/**/*.md'

variables:
  - template: '/.azuredevops/pipelineVariables/global.variables.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/arm/Microsoft.Authorization/policyExemptions'

stages:
  - stage: Validation
    displayName: Pester tests
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.validateModulePester.yml

  - stage: Deployment
    displayName: Deployment tests
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
        parameters:
          removeDeployment: '${{ parameters.removeDeployment }}'
          deploymentBlocks:
            - path: $(modulePath)/.parameters/mg.min.parameters.json
              templateFilePath: $(modulePath)/deploy.bicep
            - path: $(modulePath)/.parameters/mg.parameters.json
              templateFilePath: $(modulePath)/deploy.bicep
            - path: $(modulePath)/.parameters/sub.min.parameters.json
              templateFilePath: $(modulePath)/deploy.bicep
            - path: $(modulePath)/.parameters/sub.parameters.json
              templateFilePath: $(modulePath)/deploy.bicep
            - path: $(modulePath)/.parameters/rg.min.parameters.json
              templateFilePath: $(modulePath)/deploy.bicep
            - path: $(modulePath)/.parameters/rg.parameters.json
              templateFilePath: $(modulePath)/deploy.bicep

  - stage: Publishing
    displayName: Publish module
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq('${{ parameters.prerelease }}', 'true')))
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.publishModule.yml
