name: 'ContainerService - ManagedClusters'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

pr: none

trigger:
  batch: true
  branches:
    include:
      - work
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.containerservice.managedclusters.yml'
      - '/.azuredevops/pipelineTemplates/*.yml'
      - '/modules/Microsoft.ContainerService/managedClusters/*'
      - '/utilities/pipelines/*'
    exclude:
      - '/utilities/pipelines/dependencies/*'
      - '/**/*.md'

variables:
  - template: '../../global.variables.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/modules/Microsoft.ContainerService/managedClusters'

stages:
  - template: /.azuredevops/pipelineTemplates/stages.module.yml
    parameters:
      removeDeployment: '${{ parameters.removeDeployment }}'
      prerelease: '${{ parameters.prerelease }}'
