name: 'HealthcareApis - Workspaces'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.healthcareapis.workspaces.yml'
      - '/.azuredevops/pipelineTemplates/*.yml'
      - '/modules/Microsoft.HealthcareApis/workspaces/*'
      - '/utilities/pipelines/*'
    exclude:
      - '/utilities/pipelines/deploymentRemoval/*'
      - '/**/*.md'

variables:
  - template: '../../settings.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/modules/Microsoft.HealthcareApis/workspaces'

stages:
  - template: /.azuredevops/pipelineTemplates/stages.module.yml
    parameters:
      removeDeployment: '${{ parameters.removeDeployment }}'
      prerelease: '${{ parameters.prerelease }}'
