name: 'Network - VirtualNetworks'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

pr: none

trigger:
  batch: true
  branches:
    include:
      - work
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.network.virtualnetworks.yml'
      - '/.azuredevops/pipelineTemplates/*.yml'
      - '/modules/Microsoft.Network/virtualNetworks/*'
      - '/utilities/pipelines/*'
    exclude:
      - '/utilities/pipelines/dependencies/*'
      - '/**/*.md'

variables:
  - template: '../../global.variables.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/modules/Microsoft.Network/virtualNetworks'

stages:
  - template: /.azuredevops/pipelineTemplates/stages.module.yml
    parameters:
      removeDeployment: '${{ parameters.removeDeployment }}'
      prerelease: '${{ parameters.prerelease }}'
