name: 'Network - VirtualNetworkGateways'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: versioningOption
    displayName: The mode to handle the version increments [major|minor|patch]
    type: string
    default: patch
    values:
      - patch
      - minor
      - major
  - name: customVersion
    displayName: Custom version to apply. Used only if higher than latest
    type: string
    default: '0.0.1'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.network.virtualnetworkgateways.yml'
      - '/.azuredevops/pipelineTemplates/module.*.yml'
      - '/arm/Microsoft.Network/virtualNetworkGateways/*'
    exclude:
      - '/**/*.md'

variables:
  - template: '/.azuredevops/pipelineVariables/global.variables.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/arm/Microsoft.Network/virtualNetworkGateways'

stages:
  - stage: Pester tests
    jobs:
      - template: /.azuredevops/pipelineTemplates/module.jobs.validate.yml

  - stage: Deployment tests
    jobs:
      - template: /.azuredevops/pipelineTemplates/module.jobs.deploy.yml
        parameters:
          removeDeployment: '${{ parameters.removeDeployment }}'
          deploymentBlocks:
            - path: $(modulePath)/.parameters/expressRoute.parameters.json
            - path: $(modulePath)/.parameters/vpn.parameters.json

  - stage: Publish module
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - template: /.azuredevops/pipelineTemplates/module.jobs.publish.yml
        parameters:
          versioningOption: '${{ parameters.versioningOption }}'
          customVersion: '${{ parameters.customVersion }}'
