name: 'Synapse - Workspaces'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: versioningOption
    displayName: The mode to handle the version increments [major|minor|patch]
    type: string
    default: patch
    values:
      - patch
      - minor
      - major
  - name: customVersion
    displayName: Custom version to apply. Used only if higher than latest
    type: string
    default: '0.0.1'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.synapse.workspaces.yml'
      - '/.azuredevops/pipelineTemplates/module.*.yml'
      - '/arm/Microsoft.Synapse/workspaces/*'
    exclude:
      - '/**/*.md'

variables:
  - template: '/.azuredevops/pipelineVariables/global.variables.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/arm/Microsoft.Synapse/workspaces'

stages:
  - stage: Validation
    displayName: Pester tests
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.validateModulePester.yml

  - stage: Deployment
    displayName: Deployment tests
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
        parameters:
          removeDeployment: '${{ parameters.removeDeployment }}'
          deploymentBlocks:
            - path: $(modulePath)/.parameters/min.parameters.json
            - path: $(modulePath)/.parameters/basic.parameters.json
            - path: $(modulePath)/.parameters/encryptionwsai.parameters.json
            - path: $(modulePath)/.parameters/encryptionwuai.parameters.json
            - path: $(modulePath)/.parameters/managedvnet.parameters.json

  - stage: Publishing
    displayName: Publish module
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.publishModule.yml
        parameters:
          versioningOption: '${{ parameters.versioningOption }}'
          customVersion: '${{ parameters.customVersion }}'
