name: 'Security - AzureSecurityCenter'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: false # Needs custom removals script
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.security.azuresecuritycenter.yml'
      - '/.azuredevops/pipelineTemplates/*.yml'
      - '/modules/Microsoft.Security/azureSecurityCenter/*'
      - '/modules/.global/global.module.tests.ps1'
    exclude:
      - '/**/*.md'

variables:
  - template: '../../global.variables.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/modules/Microsoft.Security/azureSecurityCenter'

stages:
  - template: /.azuredevops/pipelineTemplates/stages.module.yml
    parameters:
      removeDeployment: '${{ parameters.removeDeployment }}'
      prerelease: '${{ parameters.prerelease }}'
      templateFilePath: '$(modulePath)/deploy.bicep'
