@description('Required. Name for the container group.')
param name string

@description('Required. The containers and their respective config within the container group.')
param containers array

@description('Optional. Ports to open on the public IP address. Must include all ports assigned on container level.')
param ipAddressPorts array = []

@description('Optional. The operating system type required by the containers in the container group. - Windows or Linux.')
param osType string = 'Linux'

@allowed([
  'Always'
  'OnFailure'
  'Never'
])
@description('Optional. Restart policy for all containers within the container group. - Always: Always restart. OnFailure: Restart on failure. Never: Never restart. - Always, OnFailure, Never.')
param restartPolicy string = 'Always'

@allowed([
  'Public'
  'Private'
])
@description('Optional. Specifies if the IP is exposed to the public internet or private VNET. - Public or Private.')
param ipAddressType string = 'Public'

@description('Optional. The image registry credentials by which the container group is created from.')
param imageRegistryCredentials array = []

@description('Optional. Location for all Resources.')
param location string = resourceGroup().location

@allowed([
  'Noreuse'
  'ResourceGroupReuse'
  'SubscriptionReuse'
  'TenantReuse'
  'Unsecure'
])
@description('Optional. Specify level of protection of the domain name label.')
param autoGeneratedDomainNameLabelScope string = 'TenantReuse'

@description('Optional. The Dns name label for the resource.')
param dnsNameLabel string = ''

@allowed([
  'Standard'
  'Dedicated'
])
@description('Optional. Specify the Sku.')
param sku string = 'Standard'

@description('Optional. If Non-Microsoft-managed encryption should be used, specify the key vaults base url.')
param encryptionVaultBaseUrl string = ''

@description('Optional. If Non-Microsoft-managed encryption should be used, specify the key name.')
param encrytionKeyName string = ''

@description('Optional. If Non-Microsoft-managed encryption should be used, specify the key version.')
param encryptionKeyVersion string = ''

@description('Optional. List of dns servers used by the containers for lookups.')
param dnsNameServers array = []

@description('Optional. DNS search domain which will be appended to each DNS lookup.')
param dnsSearchDomains string = ''

@description('Optional. A list of container definitions which will be executed before the application container starts.')
param initContainers array = []

@description('Optional. Resource ID of the subnet. Only specify when ipAddressType is Private.')
param subnetId string = ''

@description('Optional. Specify if volumes (emptyDir, AzureFileShare or GitRepo) shall be attached to your containergroup.')
param volumes array = []

@allowed([
  ''
  'CanNotDelete'
  'ReadOnly'
])
@description('Optional. Specify the type of lock.')
param lock string = ''

@description('Optional. Enables system assigned managed identity on the resource.')
param systemAssignedIdentity bool = false

@description('Optional. The ID(s) to assign to the resource.')
param userAssignedIdentities object = {}

@description('Optional. Tags of the resource.')
param tags object = {}

@description('Optional. Enable telemetry via the Customer Usage Attribution ID (GUID).')
param enableDefaultTelemetry bool = true

var identityType = systemAssignedIdentity ? (!empty(userAssignedIdentities) ? 'SystemAssigned,UserAssigned' : 'SystemAssigned') : (!empty(userAssignedIdentities) ? 'UserAssigned' : 'None')

var identity = identityType != 'None' ? {
  type: identityType
  userAssignedIdentities: !empty(userAssignedIdentities) ? userAssignedIdentities : null
} : null

var dnsConfig = !empty(dnsNameServers) ? {
  nameServers: dnsNameServers
  searchDomains: dnsSearchDomains
} : null

var encryptionProperties = !empty(encryptionVaultBaseUrl) ? {
  vaultBaseUrl: encryptionVaultBaseUrl
  keyName: encrytionKeyName
  keyVersion: encryptionKeyVersion
} : null

var basicContainerProperties = {
  containers: containers
    dnsConfig: dnsConfig
    encryptionProperties: encryptionProperties
    imageRegistryCredentials: imageRegistryCredentials
    initContainers: initContainers
    restartPolicy: restartPolicy
    osType: osType
    ipAddress: {
      type: ipAddressType
      autoGeneratedDomainNameLabelScope: autoGeneratedDomainNameLabelScope
      dnsNameLabel: dnsNameLabel
      ports: ipAddressPorts
    }
    sku: sku
    subnetIds: [
      {
        id: subnetId
      }
    ]
    volumes: volumes
}

var containerProperties = !empty(dnsNameServers) ? union(basicContainerProperties,{ dnsConfig: dnsConfig}) : basicContainerProperties

resource defaultTelemetry 'Microsoft.Resources/deployments@2021-04-01' = if (enableDefaultTelemetry) {
  name: 'pid-47ed15a6-730a-4827-bcb4-0fd963ffbd82-${uniqueString(deployment().name, location)}'
  properties: {
    mode: 'Incremental'
    template: {
      '$schema': 'https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#'
      contentVersion: '1.0.0.0'
      resources: []
    }
  }
}

resource containergroup 'Microsoft.ContainerInstance/containerGroups@2021-10-01' = {
  name: name
  location: location
  identity: identity
  tags: tags
  properties: containerProperties
}

resource containergroup_lock 'Microsoft.Authorization/locks@2017-04-01' = if (!empty(lock)) {
  name: '${containergroup.name}-${lock}-lock'
  properties: {
    level: any(lock)
    notes: lock == 'CanNotDelete' ? 'Cannot delete resource or child resources.' : 'Cannot modify the resource or child resources.'
  }
  scope: containergroup
}

@description('The name of the container group.')
output name string = containergroup.name

@description('The resource ID of the container group.')
output resourceId string = containergroup.id

@description('The resource group the container group was deployed into.')
output resourceGroupName string = resourceGroup().name

@description('The IPv4 address of the container group.')
output iPv4Address string = containergroup.properties.ipAddress.ip

@description('The principal ID of the system assigned identity.')
output systemAssignedPrincipalId string = systemAssignedIdentity && contains(containergroup.identity, 'principalId') ? containergroup.identity.principalId : ''

@description('The location the resource was deployed into.')
output location string = containergroup.location
