# NOTE:
# This pipeline requires a secret 'PLATFORM_REPO_UPDATE_PAT' set up in a library named 'PLATFORM_VARIABLES'.
# The secret's value should be a PAT token with the permissions to push to the repository's main branch.

name: '.Platform - Sync Docs/Wiki'

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'docs/wiki/**'

variables:
  - group: 'PLATFORM_VARIABLES'
  - template: '../../global.variables.yml'
  - name: pipelinePrincipalGitUserName
    value: 'CARMLPipelinePrincipal'
  - name: pipelinePrincipalGitUserEmail
    value: 'CARML@noreply.github.com'

jobs:
  - job: Update_module_tables
    pool:
      ${{ if ne('$(vmImage)', '') }}:
        vmImage: '$(vmImage)'
      ${{ if ne('$(poolName)', '') }}:
        name: '$(poolName)'
    steps:
      - checkout: self
        displayName: Checkout Source Repo
        persistCredentials: true
      # Create a variable
      - task: PowerShell@2
        displayName: 'Checkout Wiki Repo'
        inputs:
          targetType: inline
          pwsh: true
          script: |
            git config --global user.email '$(pipelinePrincipalGitUserEmail)'
            git config --global user.name '$(pipelinePrincipalGitUserName)'
            $repositoryEndpoint= 'https://' + '$(PLATFORM_REPO_UPDATE_PAT)' + '@github.com/' + '$(Build.Repository.Name)' + '.wiki'
            git clone $repositoryEndpoint
      - task: PowerShell@2
        displayName: 'Sync docs/wiki Into Wiki Repo'
        inputs:
          targetType: inline
          pwsh: true
          script: |
            $docsPath = Join-Path '$(System.DefaultWorkingDirectory)' 'docs' 'wiki'
            $wikiPath = ('$(Build.Repository.Name)').split('/')[1] + '.wiki'
            $wikiRepository = Join-Path '$(System.DefaultWorkingDirectory)' $wikiPath
            rsync -avzr --delete --exclude='.git/' $docsPath $wikiRepository
            cd $wikiRepository
            git add .
            git commit -m "Push updated Wiki"
            git push
