---
# Synopsis: Suppress Rules for min tests
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: 'SuppressMin'
spec:
  rule:
   - Azure.Resource.UseTags
   - Azure.KeyVault.Logs
  if:
    name: '.'
    contains:
      - 'min'

