---
# Synopsis: Suppress Rules for min tests
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: 'SuppressMin'
spec:
  rule:
    - Azure.Resource.UseTags
    - Azure.KeyVault.Logs
    - Azure.KeyVault.Firewall
    - Azure.Policy.ExemptionDescriptors
    - Azure.Policy.Descriptors
    - Azure.Policy.AssignmentDescriptors
    - Azure.PublicIP.AvailabilityZone
  if:
    name: '.'
    contains:
      - 'min'
