#########################################################
## 'Deploy module' Composite Action                    ##
#########################################################
##
## This composite action contains the logic to both test and execute a deployment of a given template and parameter file.
## By default, tested deployments are also removed. Optionally, the removal step can be skipped.
##
#########################################################
##
##-------------------------------------------##
## ACTION PARAMETERS                         ##
##-------------------------------------------##
##
##   |=====================================================================================================================================================================================|
##   | Parameter                 | Required | Default | Description                                           | Example                                                                    |
##   |---------------------------|----------|---------|-------------------------------------------------------|----------------------------------------------------------------------------|
##   | templateFilePath          | true     | ''      | The path to the template file to use for deployment   | 'modules/Microsoft.ApiManagement/service/deploy.bicep'                     |
##   | parameterFilePath         | true     | ''      | The path to the parameter file to use for deployment  | 'modules/Microsoft.ApiManagement/service/.test/parameters.json'            |
##   | location                  | true     | ''      | The location to use for deployment                    | 'WestEurope'                                                               |
##   | resourceGroupName         | false    | ''      | The resource group to deploy to                       | 'validation-rg'                                                            |
##   | subscriptionId            | false    | ''      | The subscriptionId to deploy to                       | '1a97b80a-4dda-4f50-ab53-349e29344654'                                     |
##   | managementGroupId         | false    | ''      | The managementGroupId to deploy to                    | '1a97b80a-4dda-4f50-ab53-349e29344654'                                     |
##   | customParameterFileTokens | false    | ''      | Additional parameter file token pairs in json format. | '{"tokenName":"tokenValue"}'                                               |
##   | removeDeployment          | false    | 'true'  | Set "true" to set module up for removal               | 'true'                                                                     |
##   |=====================================================================================================================================================================================|
##
#########################################################
##
##----------------------------------------##
## ACTION OUTPUTS                         ##
##----------------------------------------##
##
##   |================================================================|
##   | Output           | Description                                 |
##   |------------------|---------------------------------------------|
##   | deploymentOutput | The module deployment output in json format |
##   |================================================================|
##
##---------------------------------------------##

name: 'Deploy module'
description: 'Deploy module'

inputs:
  templateFilePath:
    description: 'The path to the template file to use for deployment'
    required: true
  parameterFilePath:
    description: 'The path to the parameter file to use for deployment'
    required: true
  location:
    description: 'The location to use for deployment'
    required: true
  resourceGroupName:
    description: 'The resource group to deploy to'
    required: false
  subscriptionId:
    description: 'The subscriptionId to deploy to'
    required: false
  managementGroupId:
    description: 'The managementGroupId to deploy to'
    required: false
  customParameterFileTokens:
    description: 'Additional parameter file token pairs in json format. e.g. {"tokenName":"tokenValue"}'
    required: false
  removeDeployment:
    description: 'Set "true" to set module up for removal'
    default: 'true'
    required: false

outputs:
  deploymentOutput:
    description: 'The module deployment output in json format'
    value: ${{ steps.deploy_step.outputs.deploymentOutput }}

runs:
  using: 'composite'
  steps:
    # [Setup] task(s)
    # ---------------
    - name: 'Setup agent'
      shell: pwsh
      run: |
        # Grouping task logs
        Write-Output "::group::Setup agent"

        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'sharedScripts' 'Set-EnvironmentOnAgent.ps1')

        # Define PS modules to install on the runner
        $Modules = @(
            @{ Name = 'Az.Accounts' },
            @{ Name = 'Az.Resources' }
        )

        # Additional PS modules need to be installed for the removal step in case it is enabled
        if ('${{ inputs.removeDeployment}}' -eq 'true') {
          $Modules += @(
            @{ Name = 'Az.CognitiveServices' },
            @{ Name = 'Az.Compute' },
            @{ Name = 'Az.KeyVault' },
            @{ Name = 'Az.Monitor' },
            @{ Name = 'Az.OperationalInsights' },
            @{ Name = 'Az.RecoveryServices' }
          )
        }

        # Set agent up
        Set-EnvironmentOnAgent -PSModules $Modules

        # Set additional environment variables
        # ------------------------------------
        $context = Get-AzContext

        ## Service Principal Object ID
        $servicePrincipalAppId = $Context.Account.Id
        $servicePrincipal = Get-AzADServicePrincipal -ApplicationId $servicePrincipalAppId
        $servicePrincipalObjectId = $servicePrincipal.Id
        Write-Output ('::set-output name={0}::{1}' -f 'DEPLOYMENT_SPN_ENTAPP_OBJID', $servicePrincipalObjectId)

        Write-Output "::endgroup::"

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    # [Token replacement] task(s)
    # ---------------------------
    - name: 'Replace Parameter File Tokens [${{ inputs.parameterFilePath }}] '
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          # Grouping task logs
          Write-Output "::group::Replace Parameter File Tokens [${{ inputs.parameterFilePath }}]"

          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'tokensReplacement' 'Convert-TokensInFile.ps1')

          # Load Settings File
          $Settings = Get-Content -Path "settings.json" | ConvertFrom-Json -AsHashTable

          # Construct Token Function Input
          $ConvertTokensInputs = @{
            Tokens       = @{}
            FilePath     = '${{ inputs.parameterFilePath }}'
            TokenPrefix  = $Settings.parameterFileTokens.tokenPrefix
            TokenSuffix  = $Settings.parameterFileTokens.tokenSuffix
          }

          # Local tokens
          $ConvertTokensInputs.Tokens += @{
            resourceGroupName = '${{ inputs.resourceGroupName }}'
            subscriptionId    = '${{ inputs.subscriptionId }}'
            managementGroupId = '${{ inputs.managementGroupId }}'
            tenantId          = '${{ env.ARM_TENANT_ID }}'
            deploymentSpId    = '${{ env.DEPLOYMENT_SPN_ENTAPP_OBJID }}'
          }

          # Add local tokens
          if ($Settings.parameterFileTokens.localTokens) {
            $tokenMap = @{}
            foreach ($token in $Settings.parameterFileTokens.localTokens) {
              $tokenMap += @{ $token.name = $token.value }
            }
            Write-Verbose ('Using local tokens [{0}]' -f ($tokenMap.Keys -join ', ')) -Verbose
            $ConvertTokensInputs.Tokens += $tokenMap
          }

          # Add custom tokens (passed in via the pipeline)
          if(-not [String]::IsNullOrEmpty('${{  inputs.customParameterFileTokens }}')) {
            $customTokens = '${{ inputs.customParameterFileTokens }}' | ConvertFrom-Json -AsHashTable
            Write-Verbose ('Using custom parameter file tokens [{0}]' -f ($customTokens.Keys -join ', ')) -Verbose
            $ConvertTokensInputs.Tokens += $customTokens
          }

          # Invoke Token Replacement Functionality
          $null = Convert-TokensInFile @ConvertTokensInputs

          Write-Output "::endgroup::"

    # [Deployment validation] task(s)
    # -------------------------------
    - name: 'Validate [${{ inputs.templateFilePath }}]'
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          # Grouping task logs
          Write-Output "::group::Validate [${{ inputs.templateFilePath }}]"

          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'resourceDeployment' 'Test-TemplateDeployment.ps1')

          # ----------- #
          # INVOKE TEST #
          # ----------- #
          $functionInput = @{
            templateFilePath     = '${{ inputs.templateFilePath }}'
            location             = '${{ inputs.location }}'
            resourceGroupName    = '${{ inputs.resourceGroupName }}'
            subscriptionId       = '${{ inputs.subscriptionId }}'
            managementGroupId    = '${{ inputs.managementGroupId }}'
            additionalParameters = @{}
          }

          if(-not [String]::IsNullOrEmpty('${{ inputs.parameterFilePath }}')) {
            $functionInput['parameterFilePath'] = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.parameterFilePath }}'
          }

          $projectSettings = Get-Content -Path 'settings.json' | ConvertFrom-Json
          if (-not [String]::IsNullOrEmpty($projectSettings.enableDefaultTelemetry) -and (Get-Content -Path $functionInput.templateFilePath -Raw) -like '*param enableDefaultTelemetry*') {
              $functionInput['additionalParameters'] += @{
                  enableDefaultTelemetry = $projectSettings.enableDefaultTelemetry
              }
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Test-TemplateDeployment @functionInput -Verbose

          Write-Output "::endgroup::"

    # [Deployment execution] task(s)
    # ------------------------------
    - name: 'Deploy [${{ inputs.templateFilePath }}] with parameters [${{ inputs.parameterFilePath }}]'
      id: deploy_step
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          # Grouping task logs
          Write-Output "::group::Deploy [${{ inputs.templateFilePath }}] with parameters [${{ inputs.parameterFilePath }}]"

          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'resourceDeployment' 'New-TemplateDeployment.ps1')

          $functionInput = @{
            templateFilePath     = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.templateFilePath }}'
            location             = '${{ inputs.location }}'
            resourceGroupName    = '${{ inputs.resourceGroupName }}'
            subscriptionId       = '${{ inputs.subscriptionId }}'
            managementGroupId    = '${{ inputs.managementGroupId }}'
            doNotThrow           = $true
            additionalParameters = @{}
          }

          if(-not [String]::IsNullOrEmpty('${{ inputs.parameterFilePath }}')) {
            $functionInput['parameterFilePath'] = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.parameterFilePath }}'
          }

          $projectSettings = Get-Content -Path 'settings.json' | ConvertFrom-Json
          if (-not [String]::IsNullOrEmpty($projectSettings.enableDefaultTelemetry) -and (Get-Content -Path $functionInput.templateFilePath -Raw) -like '*param enableDefaultTelemetry*') {
              $functionInput['additionalParameters'] += @{
                  enableDefaultTelemetry = $projectSettings.enableDefaultTelemetry
              }
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          # Invoke deployment
          $res = New-TemplateDeployment @functionInput -Verbose

          # Get deployment name
          Write-Output ('::set-output name={0}::{1}' -f 'deploymentName', $res.deploymentName)

          # Populate further outputs
          $deploymentOutputHash=@{}

          foreach ($outputKey in $res.deploymentOutput.Keys) {
            Write-Output ('::set-output name={0}::{1}' -f $outputKey, $res.deploymentOutput[$outputKey].Value)
            $deploymentOutputHash.add($outputKey,$res.deploymentOutput[$outputKey].Value)
          }

          $deploymentOutput = $deploymentOutputHash | ConvertTo-Json -Compress -Depth 100
          Write-Verbose "Deployment output: $deploymentOutput" -Verbose
          Write-Output ('::set-output name={0}::{1}' -f 'deploymentOutput', $deploymentOutput)

          if ($res.ContainsKey('exception')) {
            # Happens only if there is an exception
            throw $res.exception
          }

          Write-Output "::endgroup::"

    # [Deployment removal] task(s)
    # ----------------------------
    - name: 'Remove [${{ inputs.templateFilePath }}] from parameters [${{ inputs.parameterFilePath }}]'
      if: ${{ always() && inputs.removeDeployment == 'true' && steps.deploy_step.outputs.deploymentName != '' }}
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          # Grouping task logs
          Write-Output "::group::Remove [${{ inputs.templateFilePath }}] from parameters [${{ inputs.parameterFilePath }}]"

          # Load used function
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'resourceRemoval' 'Initialize-DeploymentRemoval.ps1')

          if (-not [String]::IsNullOrEmpty('${{ steps.deploy_step.outputs.deploymentName }}')) {
            $functionInput = @{
              DeploymentName    = '${{ steps.deploy_step.outputs.deploymentName }}'
              TemplateFilePath  = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.templateFilePath }}'
              ResourceGroupName = '${{ inputs.resourceGroupName }}'
              ManagementGroupId = '${{ inputs.managementGroupId }}'
              Verbose           = $true
            }

            Write-Verbose 'Invoke task with' -Verbose
            Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

            Initialize-DeploymentRemoval @functionInput
          }

          Write-Output "::endgroup::"
