name: 'Get parameter files'
description: 'Retrieve the parameter file paths of a given module'

inputs:
  modulePath:
    description: "The path to the module's folder"
    required: true

outputs:
  parameterFilePaths:
    description: 'The parameter files to use for template evaluation'
    value: ${{ steps.get-parameter-file-paths.outputs.deploymentTestPaths }}

runs:
  using: 'composite'
  steps:
    - name: 'Get parameter file paths'
      id: get-parameter-file-paths
      shell: pwsh
      run: |
        # Grouping task logs
        Write-Output "::group::Get parameter files"
        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'sharedScripts' 'Get-DeploymentTestFileList.ps1')
        $functionInput = @{
          ModulePath = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.modulePath }}'
        }
        Write-Verbose "Invoke task with" -Verbose
        Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose
        # Get the list of parameter file paths
        $deploymentTestPaths = Get-DeploymentTestFileList @functionInput -Verbose
        # Output values to be accessed by next jobs
        $compressedOutput = $deploymentTestPaths | ConvertTo-Json -Compress
        if($compressedOutput -notmatch "\[.*\]") {
          $compressedOutput = "[$compressedOutput]"
        }
        Write-Verbose "Publishing output: $compressedOutput" -Verbose
        Write-Output "::set-output name=deploymentTestPaths::$compressedOutput"
        Write-Output "::endgroup::"
