name: 'Remove module'
description: 'Remove module'

inputs:
  moduleName:
    description: 'The name of the module to remove'
    required: true
  templateFilePath:
    description: 'The path to the template file set for removal. Used to determine the type of resource.'
    required: true
  resourceGroupName:
    description: 'The resource group the module is deployed into'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Setup agent & login'
      shell: pwsh
      run: |
        # Load used functions
        . ".github/actions/sharedScripts/Set-EnvironmentOnAgent.ps1"
        # Set agent up
        Set-EnvironmentOnAgent

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: 'Remove module'
      shell: pwsh
      run: |
        # Load used functions
        . "$env:GITHUB_ACTION_PATH/scripts/Remove-DeployedModule.ps1"

        $functionInput = @{
          moduleName        = '${{ inputs.moduleName }}'
          resourceGroupName = '${{ inputs.resourceGroupName }}'
          templateFilePath  = '${{ inputs.templateFilePath }}'
        }

        Write-Verbose "Invoke task with" -Verbose
        Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

        Remove-DeployedModule @functionInput -Verbose
