name: '.Platform: Assign Pull Request to Author'
on:
  pull_request:
    types: [opened]

jobs:
  autoassign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@0a2c53d3721e4c5cfcce6afd4014aecc337979f6 # v2.0.2
        with:
          configuration-path: '.github/platform.assignPrToAuthor.configuration.yml'
